version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn install
            yarn build
            yarn run test
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build CLI
          command: |
            yarn install
            yarn build
            echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
            yarn publish from-git

workflows:
  version: 2
  monorepo:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
