version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn install
            yarn run test
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build CLI
          command: yarn run publish-all
workflows:
  version: 2
  monorepo:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master