version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8
jobs:
  check-version-cli:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Checks if cli version is published
          command: |
            cd packages/cli
            cat ./packages.json
  test-cli:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test CLI
          command: echo "Testing CLI"
  build-cli:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build CLI
          command: echo "Build CLI"
  test-common:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test Common
          command: echo "Testing Common"
  test-ui:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test UI
          command: echo "Testing UI"
workflows:
  version: 2
  cli:
    jobs:
      - check-version-cli
      - test-cli
      - build-cli:
          requires: 
            - test-cli
            - check-version-cli
  common:
    jobs:
      - test-common
  ui:
    jobs:
      - test-ui
